---
title: "August Flows and Chinook Salmon Productivity"
description: Empirical relationship between August low flows and Chinook Salmon productivity
author: "Warkentin et al. 2022"
date: "January 1, 2021"
categories:
  - "low flows"
  - "productivity"
---

### Stressor:

mean August flows during the rearing season (Nicola Mainstem)

### Species:

Chinook Salmon

### Life Stage:

All (compiled to S/R productivity estimate)

### Season/Activity:

All (compiled to S/R productivity estimate)

### Vital Rate:

Net productivity

### Citation:

*Warkentin, L., Parken, C. K., Bailey, R., & Moore, J. W. (2022). Low summer river flows associated with low productivity of Chinook salmon in a watershed with shifting hydrology. Ecological Solutions and Evidence, 3(1), e12124.*

### Stressor-Response Relationship:

#### Rationale:

...

#### Underlying Function:

...

![(Warkinton et al 2011) Effect of mean August flow during rearing on recruitment of Nicola River Chinook salmon. The three shaded regions represent 90% credible intervals of model predictions based on three spawner abundances (mean, 25th percentile and 75th percentile). The dotted horizontal line shows the replacement level of one recruit per spawner at mean spawner abundance. The vertical dashed grey line indicates the model-predicted value of 10.6 m3s−1 flow during the rearing summer that results in replacement (recruits/spawner = 1). Rugplots (grey ticks along inside of x and y axes) show distribution of observations.](/stressor_response/images/Screenshot%202023-07-12%20153453.png){fig-align="center"}
