---
  title: "Low Flows"
  listing:
  - id: stressor-magnitude
    contents:
      - "../data_and_tools/*.qmd"
    type: grid
    include:
      categories: "low flows"
  - id: stressor-response
    contents:
      - "../stressor_response/*.qmd"
    fields: [author, title, description]
    type: table
    include:
      categories: "low flows"
  - id: restoration-actions
    contents:
      - "../restoration_actions/*.qmd"
    type: grid
    include:
      categories: "low flows"
---

Impacts from low stream flows on Chinook Salmon

## **Overview**

Stream flow is a state variable in lotic systems. It has a strong control on fish habitat characteristics including temperature, sedimentation, stream morphology and dissolved oxygen. Continued changes in climate will generally favor an earlier spring freshet, and extended periods of low flow through the late summer and fall. Increasing demand (i.e., withdrawls), forestry, and urban development can further alter the hydrology of the Nicola Basin (i.e., magnitude of peak flow, timing of flow; e.g.,Winkler et al., 2017).

**Landscape activities and exacerbating factors**: Low flows are governed by climate and watershed attributes. Low flows coincide with high stream temperatures in the August/September period. Exacerbating factors include water withdrawals for agriculture, shifts in landcover (elevated evapotranspiration) as well as changes to the channel morphology and corresponding fish passage issues.

## **Key Datasets: Stressor Magnitude**

*Stressor magnitude input data is used to generate maps and location-specific estimates of current (or future) conditions across the landscape.*

::: {#stressor-magnitude}
:::

## **Stressor-Response Relationships**

*Stressor response relationships describe the relationship between a stressor and a component of the Chinook Salmon life cycle. Low stream flows are beleived to impact multiple life stages and key processes. Low stream flows can have a negative impact on egg to smolt survival through several mechanisms, including reducing rearing habitat, raising stream temperatures, limiting the amount of invertebrate prey, and reducing survival during smolt outmigration. Extremely high flows may also impact survival, for example by physically damaging eggs at redd sites. Warkentin et al. (2022) quantified the relationship between summer flow and Chinook productivity in the Nicola River, which would capture many of the above-mentioned processes.*

::: {#stressor-response}
:::

## **Associated Restoration Actions**

Various restoration actions linked to low that may directly or indirectly mitigate impacts to Chinook Salmon.

::: {#restoration-actions}
:::

## **References**

Arthuad, D. L., Greene, C. M., Guilbault, K., and Morrow Jr., J. V. 2010. Hydrobiologia 655: 171 -- 188

Chernos, M., MacDonald, R. J., and Bobenic, T. 2022. Aquatic Refugia Analysis Support -- Streamflow and macro refugia identification in the Nicola River Watershed. MacDonald Hydrology Consultants Ltd. (August 2022).

Michel, C. J., Notch, J. J., Cordoleani, F., Ammann, A. J., and Danner, E. M. Ecosphere 12: e03498;

Warkentin, L., Parken, C. K., Bailey, R., and Moore, J. W. 2020. Ecol. Solut. Evid. 3: e12124. Winkler, R., Spittlehouse, D., and Boon S. 2017. Ecohydrology 10: e1836.
