---
  title: "Stream Temperature"
  listing:
  - id: stressor-magnitude
    contents:
      - "../data_and_tools/*.qmd"
    type: grid
    include:
      categories: "stream temperature"
  - id: stressor-response
    contents:
      - "../stressor_response/*.qmd"
    fields: [author, title, description]
    type: table
    include:
      categories: "stream temperature"
  - id: restoration-actions
    contents:
      - "../restoration_actions/*.qmd"
    type: grid
    include:
      categories: "stream temperature"
---

Impacts from elevated stream temperature on Chinook Salmon

## **Overview**

Stream temperature becomes too warm for Chinook Salmon at certain life stages. Warming temperatures can have a negative impact on egg survival, alevin/fry survival, and can increase the probability of pre-spawning mortality when mature individuals return to freshwater. High stream temperatures also create thermal barriers between mainstem and tributary sections, blocking the seasonal movement of Chinook.

**Landscape activities and exacerbating factors**: Numerous natural and anthropogenic factors influence stream temperature. Forest harvesting has been demonstrated to have an important influence on stream temperature, in addition to continued changes in climate (Gomi et al., 2006).

## **Key Datasets: Stressor Magnitude**

*Stressor magnitude input data is used to generate maps and location-specific estimates of current (or future) conditions across the landscape.*

::: {#stressor-magnitude}
:::

## **Stressor-Response Relationships**

*Stressor response relationships describe the relationship between a stressor and a component of the Chinook Salmon life cycle.*

::: {#stressor-response}
:::

## **Associated Restoration Actions**

Various restoration actions linked to stream temperature that may directly or indirectly mitigate impacts to Chinook Salmon from stream temperature.

::: {#restoration-actions}
:::
